elasticsearch:
  build: elasticsearch/
  command: elasticsearch -Des.network.host=_non_loopback_
  ports:
    - "9200:9200"
    - "9300:9300"

kibana:
  image: kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch:eshost
  environment:
    ELASTICSEARCH_URL: http://eshost:9200

logstash:
  image: logstash
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  ports:
    - "25826:25826"
    - "25826:25826/udp"
  links:
    - elasticsearch:eshost
  volumes:
    - ~/elk/logstash/conf:/etc/logstash/conf.d
